baseURL = "http://example.org/"
languageCode = "en-us"
title = "kekeLAND"
theme = "simple"
copyright = "by Keke @2020 [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/deed.zh)"
[params]
subtitle = "You Are Always Alone/"
favicon = "/<path-to-site-icon>/logo.ico"
githubUrl = "https://github.com/keke-cute/blog/"
referrer = "always"
author = "keke"
description = "..."
keywords = "blog"
[[menu.main]]
weight = 10
name = "Posts"
url = "/posts/"
[[menu.main]]
weight = 20
name = "Emacs"
url = "/posts/myemacsconf/"